#!/usr/bin/env node

import assert from "node:assert/strict";
import { cp, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { auditRepository } from "../lib/audit.mjs";
import { compareBaseline, createBaseline } from "../lib/baseline.mjs";
import { createFallbackReviewBrief, validateReviewBrief } from "../lib/brief.mjs";
import { extractStyleLibrary } from "../lib/library.mjs";
import { writeStyleLibrary } from "../lib/library-report.mjs";
import { writeReportArtifacts } from "../lib/report.mjs";
import { buildTokenContract } from "../lib/token-contract.mjs";
import { compareGovernanceSnapshots, createGovernanceSnapshot } from "../lib/governance-snapshot.mjs";
import { createVisualRegression, writeVisualRegression } from "../lib/regression.mjs";
import { buildUIKitBlueprint } from "../lib/uikit-blueprint.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const fixtures = path.join(here, "fixtures");
const bootstrapPath = path.join(fixtures, "bootstrap");
const migratePath = path.join(fixtures, "migrate");
const hybridPath = path.join(fixtures, "hybrid");
const precisionPath = path.join(fixtures, "precision");
const contextualPath = path.join(fixtures, "contextual");

async function fileSnapshot(root) {
  const output = [];
  async function visit(directory) {
    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((a, b) => a.name.localeCompare(b.name));
    for (const entry of entries) {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) await visit(absolute);
      else output.push(`${path.relative(root, absolute)}:${(await readFile(absolute)).toString("base64")}`);
    }
  }
  await visit(root);
  return output;
}

const before = await fileSnapshot(fixtures);
const bootstrap = await auditRepository(bootstrapPath);
const migrate = await auditRepository(migratePath);
const hybrid = await auditRepository(hybridPath);
const precision = await auditRepository(precisionPath);
const styleLibrary = await extractStyleLibrary(migratePath);
const tokenContract = buildTokenContract(styleLibrary);
const contextualLibrary = await extractStyleLibrary(contextualPath);
const contextualContract = buildTokenContract(contextualLibrary);
const targetColorTokens = tokenContract.targetTokens.filter((item) => item.category === "color");
assert.ok(targetColorTokens.length < styleLibrary.tokens.filter((item) => item.category === "color").length, "target color semantics should consolidate source definitions");
assert.ok(targetColorTokens.every((item) => item.description?.zh && item.description?.en));
assert.ok(targetColorTokens.every((item) => item.rationale?.zh && item.rationale?.en));
assert.ok(targetColorTokens.every((item) => item.evidenceSummary?.zh && item.evidenceSummary?.en));
const after = await fileSnapshot(fixtures);

assert.deepEqual(after, before, "audit must not modify target repositories");
assert.equal(bootstrap.recommendedLane, "Bootstrap");
assert.equal(migrate.recommendedLane, "Migrate");
assert.equal(hybrid.recommendedLane, "Hybrid");
assert.equal(precision.recommendedLane, "Hybrid");
assert.ok(migrate.conflicts.some((item) => item.type === "semantic-conflict"));
assert.ok(migrate.conflicts.some((item) => item.type === "owner-conflict"));
assert.ok(hybrid.relationships.some((item) => item.type === "adapter"));
assert.ok(!hybrid.conflicts.some((item) => item.type === "owner-conflict"));
assert.ok(precision.scan.excludedScopeEntries.some((item) => item === "docs"));
assert.ok(precision.scan.excludedScopeEntries.some((item) => item === "tests"));
assert.ok(!precision.tokenDefinitions.some((item) => item.normalizedName === "method"));
assert.ok(!precision.conflicts.some((item) => /(?:from|to)/i.test(item.title)));
assert.ok(precision.tokenOwners.some((item) => item.file === "apps/canvas/src/index.css" && item.substantial));
assert.ok(precision.tokenDefinitions.filter((item) => item.file === "apps/canvas/src/index.css").every((item) => item.selector === ":root"));
assert.ok(!precision.componentCandidates.some((item) => item.file.endsWith("RenameProjectDialog.tsx")));
assert.equal(precision.componentCandidates.find((item) => item.file === "apps/canvas/src/components/ui/Dialog.tsx")?.role, "adapter");
assert.deepEqual(precision.duplicatedPrimitives.map((item) => item.primitive), ["toast"]);
assert.equal(migrate.systemReview.modelVersion, "1.3");
assert.equal(migrate.rulesetVersion, "full-1.3.0");
assert.deepEqual(migrate.systemReview.staticLayers.map((item) => item.id), ["foundation", "atoms", "molecules", "components", "patterns"]);
assert.deepEqual(migrate.systemReview.dynamicLayers.map((item) => item.id), ["interaction-foundation", "component-behavior", "cross-component-orchestration", "flow-lifecycle"]);
const colorReview = migrate.systemReview.staticLayers.find((item) => item.id === "foundation").categories.find((item) => item.id === "color");
assert.ok(colorReview.metrics.some((item) => item.id === "primary-roles"));
assert.ok(colorReview.metrics.some((item) => item.id === "hardcoded-occurrences"));
assert.ok(colorReview.metrics.some((item) => item.id === "class-selectors"));
assert.deepEqual(colorReview.subcategories.map((item) => item.id), ["primitive-palette", "brand-action", "semantic-surface", "feedback-color", "interaction-color", "theme-scope", "data-visualization"]);
assert.equal(colorReview.colorWorkbench.architecture.systemCount, 3);
assert.equal(colorReview.colorWorkbench.architecture.paletteStatus, "partial");
assert.equal(colorReview.colorWorkbench.architecture.semanticStatus, "partial");
assert.equal(colorReview.colorWorkbench.architecture.candidateFile, "src/styles/tokens.css");
assert.equal(colorReview.colorWorkbench.systems.find((item) => item.file === "src/legacy/tokens.css")?.recommendation, "merge-deprecate");
assert.equal(colorReview.colorWorkbench.implementationApproaches.find((item) => item.sourceType === "tailwind-config")?.adapterCount, 3);
assert.ok(colorReview.colorWorkbench.roleRows.find((item) => item.role === "action-primary")?.systems.some((item) => item.tokens.length));
assert.ok(colorReview.colorWorkbench.hardcodes.some((item) => item.value === "#2255cc" && item.suggestedToken === "--color-primary"));
assert.ok(colorReview.colorWorkbench.tokenDecisions.some((item) => item.normalizedName === "color-primary" && item.action === "map-to-candidate"));
const foundationCategories = migrate.systemReview.staticLayers.find((item) => item.id === "foundation").categories;
for (const categoryId of ["typography", "spacing-density", "shape-stroke", "depth-layer"]) {
  const category = foundationCategories.find((item) => item.id === categoryId);
  assert.ok(category.foundationWorkbench, `${categoryId} must expose a designer-facing workbench`);
  assert.equal(category.foundationWorkbench.architecture.candidateFile, "src/styles/tokens.css");
  assert.ok(category.foundationWorkbench.systems.length >= 1);
  assert.ok(category.foundationWorkbench.roleRows.some((item) => item.systems.some((system) => system.tokens.length)));
  assert.ok(category.foundationWorkbench.bypasses.length >= 1);
}
assert.ok(foundationCategories.find((item) => item.id === "typography").foundationWorkbench.roleRows.find((item) => item.role === "font-family").targetTokens.length);
assert.ok(foundationCategories.find((item) => item.id === "spacing-density").foundationWorkbench.roleRows.find((item) => item.role === "control-size").targetTokens.length);
assert.ok(foundationCategories.find((item) => item.id === "shape-stroke").foundationWorkbench.roleRows.find((item) => item.role === "focus-ring").targetTokens.length);
assert.ok(foundationCategories.find((item) => item.id === "depth-layer").foundationWorkbench.roleRows.find((item) => item.role === "scrim-opacity").targetTokens.length);
const iconReview = foundationCategories.find((item) => item.id === "icon-assets");
assert.ok(iconReview.iconWorkbench);
assert.equal(iconReview.iconWorkbench.architecture.libraryCount, 1);
assert.equal(iconReview.iconWorkbench.architecture.localSvgCount, 4);
assert.ok(iconReview.iconWorkbench.sources.some((item) => item.source === "lucide-react"));
assert.ok(iconReview.iconWorkbench.grids.includes("0 0 24 24"));

assert.deepEqual(styleLibrary.categories.map((item) => item.id), ["color", "typography", "icons", "shadow", "stroke", "radius", "spacing", "opacity", "blur", "layer", "motion", "other"]);
assert.ok(styleLibrary.tokens.some((item) => item.name === "--bg-body" && item.resolvedValue === "#ffffff" && item.aliasChain.includes("--color-surface")));
assert.ok(styleLibrary.categories.find((item) => item.id === "color").groups.find((item) => item.id === "background").tokens.some((item) => item.name === "--bg-body"));
assert.ok(styleLibrary.categories.find((item) => item.id === "typography").tokenCount > 0);
assert.ok(styleLibrary.categories.find((item) => item.id === "shadow").tokenCount > 0);
assert.ok(styleLibrary.categories.find((item) => item.id === "stroke").tokenCount > 0);
assert.ok(styleLibrary.categories.find((item) => item.id === "radius").tokenCount > 0);
assert.ok(styleLibrary.categories.find((item) => item.id === "spacing").tokenCount > 0);
assert.ok(styleLibrary.categories.find((item) => item.id === "opacity").tokenCount > 0);
assert.ok(styleLibrary.categories.find((item) => item.id === "layer").tokenCount > 0);
assert.ok(styleLibrary.icons.some((item) => item.name === "check" && item.preview?.startsWith("data:image/svg+xml;base64,")));
assert.ok(styleLibrary.icons.some((item) => item.name === "check" && item.sourceStatus === "source-used" && item.productionReferenceCount > 0));
assert.ok(styleLibrary.icons.some((item) => item.name === "unused-icon" && item.governance?.recommendation === "delete" && item.governance?.deleteEligibility === "qualified-for-trial" && item.runtimeStatus === "unverified"));
assert.ok(styleLibrary.icons.find((item) => item.name === "unused-icon").governance.checks.some((item) => item.id === "source-consumers" && item.status === "passed"));
assert.ok(styleLibrary.icons.find((item) => item.name === "unused-icon").governance.checks.some((item) => item.id === "production-build" && item.status === "pending"));
assert.ok(styleLibrary.icons.find((item) => item.name === "check").governance.recommendation === "keep");
assert.ok(styleLibrary.icons.find((item) => item.name === "legacy-public-icon").governance.recommendation === "verify-external");
assert.ok(styleLibrary.icons.find((item) => item.name === "runtime-icon").governance.checks.some((item) => item.id === "dynamic-loading" && item.status === "blocked"));
assert.ok(styleLibrary.tokens.every((item) => item.usage?.definitionOwner?.file));
assert.ok(styleLibrary.directStyles.every((item) => item.usage?.evidenceLevels?.includes("source-confirmed")));
assert.ok(!styleLibrary.directStyles.some((item) => item.scene === "asset-color"));
assert.ok(styleLibrary.summary.assetInternalColorOccurrencesExcluded > 0);
assert.equal(tokenContract.framework.model, "primitive -> semantic -> component");
assert.ok(tokenContract.framework.families.some((item) => item.id === "text" && item.roles.includes("placeholder") && item.roles.includes("disabled")));
assert.ok(tokenContract.lifecycle.every((item) => ["migrate", "merge", "delete"].includes(item.action)));
assert.ok(tokenContract.lifecycle.some((item) => item.action === "delete"));

const contextualTargets = new Map(contextualContract.targetTokens.map((item) => [item.name, item]));
assert.ok(contextualTargets.has("--bg-body"), "page-root consumers must create the body semantic");
assert.ok(contextualTargets.has("--bg-surface"), "card consumers must create a surface semantic even when the rendered value matches body");
assert.ok(contextualTargets.has("--bg-elevated"), "popover content must map to an elevated surface");
assert.ok(contextualTargets.has("--bg-scrim"), "dialog backdrops must create a translucent scrim semantic");
assert.ok(contextualTargets.has("--action-primary-content"), "interactive foreground content belongs to Action, not Text");
assert.ok(contextualTargets.has("--brand-primary-subtle-surface"), "a brand primitive used on a card must remain Brand instead of becoming the global surface");
assert.equal(contextualTargets.get("--action-primary-content").group, "brand-action");
assert.ok(!contextualTargets.has("--bg-subtle"), "a same-value alias must not invent a subtle background role");
assert.ok(Object.values(contextualTargets.get("--bg-scrim").modes).every((value) => /(?:rgba|\/)/i.test(value)), "scrim modes must remain translucent");
assert.ok(contextualTargets.get("--bg-scrim").semanticEvidence.some((item) => item.reason === "consumer:scrim-layer"));
const contextualAdapters = new Map(contextualLibrary.tokens.filter((item) => item.role === "adapter").map((item) => [item.name, item.semantic]));
assert.equal(contextualAdapters.get("background")?.targetName, "--bg-body", "the JSX element around a utility class must contribute page-layer context");
assert.equal(contextualAdapters.get("muted")?.targetName, "--bg-surface", "the JSX element around a utility class must contribute surface-layer context");
assert.equal(contextualAdapters.get("mask")?.targetName, "--bg-scrim", "a Tailwind adapter must inherit the consumer semantic instead of becoming a target owner");
assert.equal(contextualAdapters.get("actionContent")?.targetName, "--action-primary-content", "interactive content adapters must remain in the Action family");
assert.ok(contextualLibrary.tokens.filter((item) => item.name === "--primitive-neutral-0").every((item) => item.semantic.targetName === null), "a shared primitive feeding incompatible consumers must remain unresolved");
assert.ok(contextualLibrary.tokens.filter((item) => item.name === "popover" && item.category === "color").every((item) => !item.aliasChain.includes("--shadow-popover")), "same-name Tailwind keys in different namespaces must not cross-resolve aliases");
assert.ok(contextualLibrary.tokens.filter((item) => item.name === "--shadow-popover").every((item) => item.semantic.targetName === null), "shadow atoms must never be inferred as background-color semantics");
assert.ok(contextualLibrary.tokens.filter((item) => item.name === "--color-shadow-sm").every((item) => item.category === "shadow"), "shadow color primitives belong to the Shadow atom rather than the global Color target library");
const contextualWhiteDirect = contextualLibrary.directStyles.filter((item) => item.category === "color" && item.normalizedColor === "#FFFFFF");
assert.ok(contextualWhiteDirect.some((item) => item.semantic.targetName === "--bg-body"), "same-value direct colors must retain page-layer context");
assert.ok(contextualWhiteDirect.some((item) => item.semantic.targetName === "--bg-surface"), "same-value direct colors must form a separate surface cluster when consumers differ");
const primitiveNeutral = contextualLibrary.tokens.find((item) => item.name === "--primitive-neutral-0" && item.scope === "global");
assert.equal(primitiveNeutral.semantic.targetName, null, "a shared primitive feeding incompatible consumers must remain semantically unresolved");
assert.ok(primitiveNeutral.semantic.conflicts.includes("multiple-consumer-semantics"));
assert.ok(contextualContract.lifecycle.some((item) => item.action === "migrate" && item.targetToken?.name === "--bg-body"));
assert.ok(contextualContract.lifecycle.some((item) => item.action === "migrate" && item.targetToken?.name === "--action-primary-content"));

const fallbackBrief = createFallbackReviewBrief(migrate);
const uikitBlueprint = buildUIKitBlueprint(migrate, styleLibrary, tokenContract, fallbackBrief);
const bootstrapLibrary = await extractStyleLibrary(bootstrapPath);
const bootstrapContract = buildTokenContract(bootstrapLibrary);
const bootstrapBlueprint = buildUIKitBlueprint(bootstrap, bootstrapLibrary, bootstrapContract, createFallbackReviewBrief(bootstrap));
assert.equal(validateReviewBrief(fallbackBrief, migrate).valid, true);
assert.equal(uikitBlueprint.model, "current-to-target-governance");
assert.equal(uikitBlueprint.componentSetup.mode, "map-existing");
assert.equal(bootstrapBlueprint.componentSetup.mode, "starter-proposal");
assert.ok(bootstrapBlueprint.componentSetup.proposedCount > 0);
assert.ok(bootstrapBlueprint.componentSetup.proposedComponentIds.includes("button"));
assert.ok(bootstrapBlueprint.componentLayers.flatMap((item) => item.nodes).find((item) => item.id === "button").proposal);
assert.deepEqual(uikitBlueprint.foundation.map((item) => item.id), ["color", "typography", "iconography", "spacing-density", "grid-layout", "size-control", "radius", "stroke", "shadow-elevation", "opacity-blur", "layer", "motion"]);
assert.deepEqual(uikitBlueprint.componentLayers.map((item) => item.id), ["atoms", "molecules", "components"]);
assert.ok(uikitBlueprint.componentLayers.find((item) => item.id === "atoms").nodes.some((item) => item.id === "button" && item.contract.states.includes("hover")));
assert.ok(uikitBlueprint.componentLayers.find((item) => item.id === "components").nodes.some((item) => item.id === "dialog" && item.contract.behavior.includes("focus trap")));
assert.ok(uikitBlueprint.actions.every((item) => ["migrate", "merge", "delete"].includes(item.action)));
const targetIconReview = uikitBlueprint.foundation.find((item) => item.id === "iconography");
const targetColorReview = uikitBlueprint.foundation.find((item) => item.id === "color");
const targetTypographyReview = uikitBlueprint.foundation.find((item) => item.id === "typography");
assert.equal(targetColorReview.currentTokens.length, styleLibrary.tokens.filter((item) => item.category === "color").length);
assert.equal(targetTypographyReview.currentTokens.length, styleLibrary.tokens.filter((item) => item.category === "typography").length);
assert.equal(targetTypographyReview.directStyles.length, styleLibrary.directStyles.filter((item) => item.category === "typography").length);
assert.ok(targetColorReview.directStyles.some((item) => item.sourceValues.includes("text-[#111111]")));
assert.ok(targetTypographyReview.directStyles.some((item) => item.value === "text-[14px]"));
assert.ok(targetColorReview.directOccurrenceCount >= targetColorReview.directClusterCount);
assert.ok(targetColorReview.directStyles.some((item) => item.normalizedColor?.startsWith("#")));
assert.ok(targetColorReview.directStyles.every((item) => Array.isArray(item.contexts) && Array.isArray(item.sourceValues)));
assert.equal(targetIconReview.assets.length, styleLibrary.icons.length);
assert.equal(targetIconReview.iconReview.summary.totalGraphicAssets, styleLibrary.icons.length);
assert.ok(targetIconReview.iconReview.summary.delete > 0);
assert.ok(targetIconReview.iconReview.summary.externalCheck >= 2);
assert.ok(targetIconReview.iconReview.batches.some((item) => item.action === "delete" && item.count > 0));
assert.equal(targetIconReview.iconReview.summary.runtimeVerified, 0);
assert.ok(uikitBlueprint.implementationSlices.length > 0);
assert.equal(fallbackBrief.schemaVersion, 2);
assert.equal(fallbackBrief.decisionPackages.length, migrate.conflicts.length);
assert.ok(fallbackBrief.decisionPackages.every((item) => item.current && item.target && item.recommendation && item.choices.length >= 2));
assert.ok(fallbackBrief.decisionPackages.every((item) => item.systemPath && item.standard));
assert.ok(fallbackBrief.decisionPackages.every((item) => item.choices.every((choice) => choice.decision === "defer" ? choice.resolutionAction === null : ["migrate", "merge", "delete"].includes(choice.resolutionAction))));
const findingsOnlyBrief = structuredClone(fallbackBrief);
findingsOnlyBrief.decisionPackages[0].conflictIds = [];
findingsOnlyBrief.decisionPackages[0].findingFingerprints = [migrate.findings[0].fingerprint];
assert.equal(validateReviewBrief(findingsOnlyBrief, migrate).valid, true);

const migrateRepeat = await auditRepository(migratePath);
assert.equal(migrate.reportId, migrateRepeat.reportId, "same source must produce the same report ID");
assert.deepEqual(migrate.findings.map((item) => item.fingerprint), migrateRepeat.findings.map((item) => item.fingerprint));

const baseline = createBaseline(migrate);
const unchanged = compareBaseline(migrateRepeat, baseline);
assert.equal(unchanged.new.length, 0);
assert.equal(unchanged.stale.length, 0);
assert.equal(unchanged.gateFindings.length, 0);

const temp = await mkdtemp(path.join(os.tmpdir(), "design-governance-test-"));
try {
  const mutableRepo = path.join(temp, "repo");
  await cp(migratePath, mutableRepo, { recursive: true });
  await writeFile(path.join(mutableRepo, "src", "new-debt.css"), ".new-debt { color: var(--color-missing-governance); }\n.new-debt:hover { color: var(--color-missing-governance); }\n", "utf8");
  const changed = await auditRepository(mutableRepo);
  const comparison = compareBaseline(changed, baseline);
  assert.ok(comparison.new.some((item) => item.ruleId === "token.undefined-reference"));
  assert.ok(comparison.gateFindings.some((item) => item.ruleId === "token.undefined-reference"));

  const reportDir = path.join(temp, "report");
  const files = await writeReportArtifacts(migrate, reportDir, { tokenContract, styleLibrary });
  assert.equal(path.basename(files.html), "design-review.html");
  assert.equal(path.basename(files.tokenContract), "govern-ui-token-contract.json");
  const html = await readFile(files.html, "utf8");
  assert.ok(html.includes("Target UIKit · Migration Blueprint"));
  assert.ok(html.includes("目标 UIKit 全景"));
  assert.ok(html.includes("Target UIKit skeleton"));
  assert.ok(html.includes("Foundation 基础规范"));
  assert.ok(html.includes("Foundation system"));
  assert.ok(html.includes("组件系统"));
  assert.ok(html.includes("Component system"));
  assert.ok(html.includes("迁移、合并与删除"));
  assert.ok(html.includes("Migrate, merge, and delete"));
  assert.ok(html.includes("待决策中心"));
  assert.ok(html.includes("Decision center"));
  assert.ok(html.includes("看元素对比，选择处理方式。"));
  assert.ok(html.includes('class="decision-stage"'));
  assert.ok(html.includes('class="specimen-board target"'));
  assert.ok(html.includes('class="decision-more"'));
  assert.ok(html.includes("实施批次与视觉验证"));
  assert.ok(html.includes("Implementation and visual validation"));
  assert.ok(html.includes("可直接迁移"));
  assert.ok(html.includes("建议删除"));
  assert.ok(html.includes("current-to-target-governance"));
  assert.ok(html.includes("componentLayers"));
  assert.ok(html.includes("componentSetup"));
  assert.ok(html.includes("implementationSlices"));
  assert.ok(html.includes("govern-ui-token-contract.json"));
  assert.ok(html.includes("govern-ui-decisions.json"));
  assert.ok(html.includes("View source evidence (engineers)"));
  assert.ok(html.includes("查看源码证据（工程师）"));
  assert.ok(html.includes("完整资产目录"));
  assert.ok(html.includes("Complete asset catalog"));
  assert.ok(html.includes("已自动给出治理建议，不要求逐项猜测"));
  assert.ok(html.includes("Governance actions are prefilled"));
  assert.ok(html.includes("删除门槛"));
  assert.ok(html.includes("Deletion gates"));
  assert.ok(html.includes('data-locale="zh"'));
  assert.ok(html.includes('data-locale="en"'));
  assert.ok(html.includes("govern-ui:locale"));
  assert.ok(html.includes("navigator.language"));
  assert.ok(html.includes('data-module-target="uikit"'));
  assert.ok(html.includes('class="reference-canvases"'));
  assert.ok(html.includes('class="color-framework"'));
  assert.ok(html.includes('color-palette-lanes'));
  assert.ok(html.includes('color-semantic-matrix'));
  assert.ok(html.includes('color-governance-summary'));
  assert.ok(html.includes('class="color-scene-head"'));
  assert.ok(html.includes('class="hardcoded-summary"'));
  assert.ok(html.includes('class="hardcoded-list"'));
  assert.ok(html.includes('Primitive = #RRGGBB / #RRGGBBAA'));
  assert.ok(html.includes('颜色写法统一'));
  assert.ok(html.includes('Color format normalization'));
  assert.ok(html.includes('源码中的直接颜色'));
  assert.ok(html.includes('Direct colors in source'));
  assert.ok(html.includes('class="type-review"'));
  assert.ok(html.includes('class="type-family-grid"'));
  assert.ok(html.includes('class="type-table"'));
  assert.ok(html.includes('class="type-direct-list"'));
  assert.ok(html.includes('目标文字体系（基于项目现状）'));
  assert.ok(html.includes('Target typography derived from the project'));
  assert.ok(html.includes('共享 UI 阶梯'));
  assert.ok(html.includes('Product-scoped scales'));
  assert.ok(html.includes('typeWeightCards'));
  assert.ok(!html.includes('CN-24-Medium'));
  assert.ok(html.includes('源码中的直接文字样式'));
  assert.ok(html.includes('Direct typography in source'));
  assert.ok(html.includes('语义 Token 补全'));
  assert.ok(html.includes('Semantic Token completion'));
  assert.ok(html.includes('--color-review-dark:#1c1c1c'));
  assert.ok(html.includes('--color-review-light:#f5f5f3'));
  assert.ok(html.includes('.color-swatch{display:inline-block;width:24px;height:24px'));
  assert.ok(html.includes('colorSemanticDecisions'));
  assert.ok(html.includes('class="governance-batches"'));
  assert.ok(html.includes('id="finish-panel"'));
  assert.ok(!html.includes('id="export-button"'));
  assert.ok(html.includes('content="light"'));
  assert.ok(!html.includes("prefers-color-scheme: dark"));
  assert.ok(html.includes("decision-search"));
  assert.ok(html.includes("packageDecisions"));
  assert.ok(html.includes("tokenLifecycleDecisions"));
  assert.ok(html.includes("directStyleDecisions"));
  assert.ok(html.includes("componentBuildDecision"));
  assert.ok(html.includes("batchApprovals"));
  assert.ok(html.includes("assetLifecycleDecisions"));
  assert.ok(html.includes("assetBatches"));
  assert.ok(!html.includes('id="stats"'));
  assert.ok(!html.includes("High-priority evidence"));
  assert.ok(html.includes("@media(max-width:820px)"));
  assert.ok(!html.includes("{{REPORT_JSON}}"));
  assert.ok(!/<script\s+[^>]*src=/i.test(html), "HTML report must not use remote scripts");
  assert.ok(!/<link\s+[^>]*href=["']https?:/i.test(html), "HTML report must not use remote styles");
  const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map((match) => match[1]);
  assert.doesNotThrow(() => new Function(scripts.at(-1)), "interactive report script must parse");

  const libraryDir = path.join(temp, "library");
  const libraryFiles = await writeStyleLibrary(styleLibrary, libraryDir);
  const scanHtml = await readFile(libraryFiles.html, "utf8");
  assert.ok(scanHtml.includes('governui.artifacts/1.1.0'));
  assert.ok(scanHtml.includes('artifact-data'));
  const libraryHtml = await readFile(libraryFiles.detail, "utf8");
  assert.ok(libraryHtml.includes("原子样式库"));
  assert.ok(libraryHtml.includes("Atomic style library"));
  assert.ok(libraryHtml.includes("背景色"));
  assert.ok(libraryHtml.includes("字体与排版"));
  assert.ok(libraryHtml.includes("投影"));
  assert.ok(libraryHtml.includes("描边"));
  assert.ok(libraryHtml.includes("完整 Token 映射"));
  assert.ok(libraryHtml.includes("--bg-body"));
  assert.ok(libraryHtml.includes("data:image/svg+xml;base64,"));
  assert.ok(libraryHtml.includes("govern-ui-token-map.json"));
  assert.ok(libraryHtml.includes("功能位置"));
  assert.ok(libraryHtml.includes("Product location"));
  assert.ok(!libraryHtml.includes("{{LIBRARY_JSON}}"));
  assert.ok(!libraryHtml.includes("High-priority evidence"));
  assert.ok(!libraryHtml.includes("Recommended lane"));
  assert.ok(!/<script\s+[^>]*src=/i.test(libraryHtml), "style library must not use remote scripts");
  assert.ok(!/<link\s+[^>]*href=["']https?:/i.test(libraryHtml), "style library must not use remote styles");
  const libraryScripts = [...libraryHtml.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map((match) => match[1]);
  assert.doesNotThrow(() => new Function(libraryScripts.at(-1)), "style-library script must parse");

  const beforeSnapshot = createGovernanceSnapshot(styleLibrary);
  const afterLibrary = structuredClone(styleLibrary);
  afterLibrary.tokens = afterLibrary.tokens.slice(1);
  afterLibrary.directStyles = afterLibrary.directStyles.slice(1);
  const afterSnapshot = createGovernanceSnapshot(afterLibrary);
  const sourceDiff = compareGovernanceSnapshots(beforeSnapshot, afterSnapshot);
  assert.equal(sourceDiff.summary.tokensRemoved, 1);
  assert.equal(sourceDiff.summary.directStylesRemoved, 1);
  const svgBefore = `data:image/svg+xml;base64,${Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="320" height="200"><rect width="320" height="200" fill="#fff"/><rect x="24" y="24" width="120" height="48" fill="#2255cc"/></svg>').toString("base64")}`;
  const svgAfter = `data:image/svg+xml;base64,${Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="320" height="200"><rect width="320" height="200" fill="#fff"/><rect x="24" y="24" width="120" height="48" fill="#2458d3"/></svg>').toString("base64")}`;
  const regression = await createVisualRegression(beforeSnapshot, afterSnapshot, { captures: [{ id: "dashboard-default", feature: "Dashboard", page: "/dashboard", state: "default", viewport: "1440x960", theme: "light", beforeImage: svgBefore, afterImage: svgAfter, affectedTokens: ["--color-primary"], expectedChange: "No visible change" }, { id: "dashboard-error", feature: "Dashboard", page: "/dashboard", state: "error", viewport: "390x844", theme: "dark" }] });
  assert.equal(regression.coverage.total, 2);
  assert.equal(regression.coverage.unverified, 1);
  const regressionFiles = await writeVisualRegression(regression, path.join(temp, "regression"));
  const regressionHtml = await readFile(regressionFiles.html, "utf8");
  assert.ok(regressionHtml.includes("视觉回归复核"));
  assert.ok(regressionHtml.includes("Before / After / Difference"));
  assert.ok(regressionHtml.includes("govern-ui-visual-decisions.json"));
  assert.ok(!regressionHtml.includes("{{REGRESSION_JSON}}"));
  assert.ok(!/<script\s+[^>]*src=/i.test(regressionHtml));
  const regressionScripts = [...regressionHtml.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map((match) => match[1]);
  assert.doesNotThrow(() => new Function(regressionScripts.at(-1)), "visual-regression script must parse");
} finally {
  await rm(temp, { recursive: true, force: true });
}

process.stdout.write(`Passed GovernUI atomic-library and design-review tests\n`);
process.stdout.write(`Bootstrap findings: ${bootstrap.findings.length}\n`);
process.stdout.write(`Migrate findings: ${migrate.findings.length}\n`);
process.stdout.write(`Hybrid findings: ${hybrid.findings.length}\n`);
process.stdout.write(`Precision findings: ${precision.findings.length}\n`);
